channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.14.3
  - cffi==1.16.0
  - click==8.1.7
  - cloudpickle==3.0.0
  - cytoolz==0.12.2
  - dask-expr==1.1.0
  - defusedxml==0.7.1
  - distributed==2024.5.0
  - graphviz==0.20.3
  - jinja2==3.1.4
  - lightgbm==4.3.0
  - lz4==4.3.2
  - matplotlib==3.8.4
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.2.2
  - pyarrow==15.0.2
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.13.1
  - setproctitle==1.2.2
  - zstandard==0.19.0
name: mlflow-env
